"""Wire the forge-built crop sheets into the FruitFarming mod.

For every crop built into dist/FFCrops (examples/ff_build.py):
  * copies its texture pack and tile definitions into the mod's ``common/media`` (where
    the user's HomeBrewing ships its packs, tiles and geometry -- the layout B42 loads),
  * merges the sheet's tile geometry into ``common/media/tileGeometry.txt`` the way
    vanilla writes growing crops: every sprite ``Translucent``, no boxes, no depth
    texture (pzforge.geometry.plant_tiles),
  * rewrites the ``pack=`` / ``tiledef=`` lines of ``42/mod.info`` (and its modversion
    when ``--version`` is given),
  * writes ``common/media/lua/server/Farming/FF_farmingSprites.lua``: the per-crop sprite
    arrays farming_vegetableconf.getSpriteName indexes with nbOfGrow (1-based), one per
    health kind, plus the props texture the seed tooltip shows. A sheet built with
    --health-variants holds 32 sprites in row order: healthy 0-7, unhealthy 8-15,
    dying 16-23, dead 24-31. Trampled stays borrowed from the vanilla habit (it is
    separate art in vanilla, IoU 0.58 -- not a colour transform). The same file wraps
    farming_vegetableconf.getSpriteName so a harvested perennial shows column 7, its
    fruiting plant without the fruit, instead of the young plant vanilla's growBack
    stage would show (ff_crop.AFTER_HARVEST).

usage:
    uv run --python 3.12 --with pillow python examples/ff_wire_mod.py [--dry-run] [--version 0.3.0] [--mod DIR]
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from pzforge import geometry as geom  # noqa: E402

DIST = ROOT / "dist" / "FFCrops" / "42" / "media"
MOD = Path(r"C:\Users\leina\Zomboid\mods\FruitFarming")

#: mod conf key -> forge sheet crop name
CROPS = {
    "FFApple": "apple", "FFPear": "pear", "FFPeach": "peach", "FFCherry": "cherry",
    "FFOrange": "orange", "FFLemon": "lemon", "FFLime": "lime", "FFGrapefruit": "grapefruit",
    "FFAvocado": "avocado", "FFMango": "mango", "FFOlive": "olive", "FFCoffee": "coffee",
    "FFPeanuts": "peanut", "FFRice": "rice", "FFBanana": "banana", "FFPineapple": "pineapple",
    "FFGrapes": "grape", "FFGinger": "ginger",
}
KINDS = (("sprite", 0), ("unhealthySprite", 8), ("dyingSprite", 16), ("deadSprite", 24))
SPRITES_PER_SHEET = 32
COLUMNS = 8

#: tiledef ids start here: HomeBrewing claims 2000-2007 (still, barrels, the 3-tier rack),
#: so the crops' first numbering (2002 up) would have overwritten its tiles in any game
#: running both mods; 2100-2117 is free across installed and workshop mods
TILEDEF_BASE = 2100
#: tiledef ids as the batch build assigned them (TILEDEF_BASE upward in this order; the
#: .tiles file itself only carries its internal tileset id). Vanilla farming tiles carry
#: exactly BlocksPlacement + attachedFloor (+CustomName), which is the vegetation preset.
ORDER = ("apple", "pear", "peach", "cherry", "orange", "lemon", "lime", "grapefruit",
         "avocado", "mango", "olive", "coffee", "peanut", "rice", "banana", "pineapple",
         "grape", "ginger")


def tiledef_id(name: str) -> int:
    crop = re.match(r"ff_(\w+)_01$", name).group(1)
    return TILEDEF_BASE + ORDER.index(crop)


def lua_text(sheets: list[tuple[str, str]]) -> str:
    out = ["-- generated by pz-sprite-forge/examples/ff_wire_mod.py -- do not edit by hand",
           "-- FruitFarming's own growth sprites: one ff_<crop>_01 sheet per crop (tiledef ids",
           f"-- {TILEDEF_BASE} up), 32 sprites each -- healthy 0-7, unhealthy 8-15, dying 16-23, dead",
           "-- 24-31, one per growth stage. getSpriteName indexes these with nbOfGrow (1-based).",
           "-- A perennial's column 7 is the plant after harvest (see the end of this file).",
           "-- Trampled art stays borrowed from the vanilla crop FF_farmingConf.lua assigns.",
           'require "Farming/farming_vegetableconf"',
           'require "Farming/FF_farmingConf"',
           "if not farming_vegetableconf then return end",
           "",
           "local KINDS = { sprite = 0, unhealthySprite = 8, dyingSprite = 16, deadSprite = 24 }",
           "local SHEETS = {}",
           "",
           "local function useSheet(key, sheet)",
           "    -- a crop FF_farmingConf.lua disabled (missing vanilla source) keeps no props",
           "    if not farming_vegetableconf.props[key] then return end",
           "    for kind, base in pairs(KINDS) do",
           "        local names = {}",
           "        for i = 0, 7 do names[#names + 1] = sheet .. \"_\" .. (base + i) end",
           "        farming_vegetableconf[kind] = farming_vegetableconf[kind] or {}",
           "        farming_vegetableconf[kind][key] = names",
           "    end",
           "    -- the picture the seed tooltip shows: the crop in fruit",
           "    farming_vegetableconf.props[key].texture = sheet .. \"_6\"",
           "    SHEETS[key] = sheet",
           "end",
           "",
           "-- Perennials keep their size after harvest. Vanilla's harvest() puts a growBack crop",
           "-- back to nbOfGrow = growBack and grows it one step, and sprite[growBack + 1] is the",
           "-- young plant of the first growth: a fruit tree shrank to a sapling every time it was",
           "-- picked. Column 7 of a perennial's sheet is its fruiting plant with the fruit taken",
           "-- off. While a plant regrows (growBack < nbOfGrow < harvestLevel) after it has fruited",
           "-- -- the sprite it shows now is column 6 (in fruit) or 7 (picked) -- it shows column 7",
           "-- in the health row vanilla chose; bloom and fruit then follow as usual. A first growth",
           "-- never shows column 6 or 7 at those stages, so it is untouched. The sprite name is",
           "-- saved with the plant and sent to clients, so this holds across save/load and in",
           "-- multiplayer, where getSpriteName runs with SFarmingSystem on the server.",
           "local function column(name, sheet)",
           "    if type(name) ~= \"string\" then return nil end",
           "    local n = string.match(name, \"^\" .. sheet .. \"_(%d+)$\")",
           "    return n and tonumber(n) or nil",
           "end",
           "",
           "local vanillaGetSpriteName = farming_vegetableconf.getSpriteName",
           "if vanillaGetSpriteName then",
           "    farming_vegetableconf.getSpriteName = function(plant)",
           "        local name = vanillaGetSpriteName(plant)",
           "        local sheet = plant and SHEETS[plant.typeOfSeed]",
           "        if not sheet or not name then return name end",
           "        local props = farming_vegetableconf.props[plant.typeOfSeed]",
           "        local nb = tonumber(plant.nbOfGrow)",
           "        if not (props and props.growBack and nb) then return name end",
           "        if nb <= props.growBack or nb >= (props.harvestLevel or 6) then return name end",
           "        local now, new = column(plant.spriteName, sheet), column(name, sheet)",
           "        if not (now and new) or now % 8 < 6 then return name end",
           "        return sheet .. \"_\" .. (new - new % 8 + 7)",
           "    end",
           "end",
           ""]
    for key, name in sheets:
        out.append(f'useSheet("{key}", "{name}")')
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--version", help="set modversion= in 42/mod.info")
    ap.add_argument("--mod", type=Path, default=MOD, help="the mod folder to wire (default: the dev copy)")
    args = ap.parse_args()
    mod = args.mod
    media = mod / "common" / "media"
    lua_path = media / "lua" / "server" / "Farming" / "FF_farmingSprites.lua"

    sheets = []
    for key, crop in CROPS.items():
        name = f"ff_{crop}_01"
        pack = DIST / "texturepacks" / f"{name}.pack"
        tiles = DIST / f"{name}.tiles"
        if not pack.exists() or not tiles.exists():
            raise SystemExit(f"{key}: {name} is not built (run examples/ff_build.py)")
        sheets.append((key, name))
    geometry = geom.file_text([geom.tileset_text(name, geom.plant_tiles(SPRITES_PER_SHEET), COLUMNS)
                               for _, name in sheets])

    info_path = mod / "42" / "mod.info"
    info = [ln for ln in info_path.read_text(encoding="utf-8").splitlines()
            if not ln.startswith(("pack=", "tiledef="))]
    if args.version:
        info = [f"modversion={args.version}" if ln.startswith("modversion=") else ln for ln in info]
        if not any(ln.startswith("modversion=") for ln in info):
            info.append(f"modversion={args.version}")
    for _, name in sheets:
        info.append(f"pack={name}")
    for _, name in sheets:
        info.append(f"tiledef={name} {tiledef_id(name)}")

    print(f"{len(sheets)} sheets -> {media}")
    print(f"mod.info: {sum(1 for ln in info if ln.startswith(('pack=', 'tiledef=')))} pack/tiledef lines"
          + (f", modversion={args.version}" if args.version else ""))
    if args.dry_run:
        print("\n".join(info))
        print(lua_text(sheets)[:900], "...")
        return
    (media / "texturepacks").mkdir(parents=True, exist_ok=True)
    for _, name in sheets:
        shutil.copy2(DIST / "texturepacks" / f"{name}.pack", media / "texturepacks" / f"{name}.pack")
        shutil.copy2(DIST / f"{name}.tiles", media / f"{name}.tiles")
    geom.merge_into(media / "tileGeometry.txt", geometry)
    info_path.write_text("\n".join(info) + "\n", encoding="utf-8")
    lua_path.parent.mkdir(parents=True, exist_ok=True)
    lua_path.write_text(lua_text(sheets), encoding="utf-8")
    size = sum((media / "texturepacks" / f"{n}.pack").stat().st_size for _, n in sheets)
    print(f"wrote {len(sheets)} packs ({size / 1e6:.1f} MB), {len(sheets)} .tiles, tileGeometry.txt, "
          f"{info_path.relative_to(mod)}, {lua_path.relative_to(mod)}")


if __name__ == "__main__":
    main()
