"""Wire the forge-built crop packs into the FruitFarming mod.

Copies each crop's .pack/.tiles into the mod's 42/media tree, rewrites the pack= /
tiledef= lines in 42/mod.info, and writes FF_farmingSprites.lua: the per-crop sprite
arrays that farming_vegetableconf.getSpriteName indexes with nbOfGrow (1-based), one
array per health kind. A pack built with --health-variants holds 32 sprites in row order:
healthy 0-7, unhealthy 8-15, dying 16-23, dead 24-31. Trampled stays borrowed from the
vanilla habit (it is separate art in vanilla, IoU 0.58 -- not a colour transform).

usage:
    uv run --python 3.12 --with pillow python examples/ff_wire_mod.py [--dry-run]
"""
from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist" / "FFCrops" / "42" / "media"
MOD = Path(r"C:\Users\leina\Zomboid\mods\FruitFarming")
MOD_MEDIA = MOD / "42" / "media"
LUA = MOD / "common" / "media" / "lua" / "server" / "Farming" / "FF_farmingSprites.lua"

#: mod conf key -> forge sheet crop name
CROPS = {
    "FFApple": "apple", "FFPear": "pear", "FFPeach": "peach", "FFCherry": "cherry",
    "FFOrange": "orange", "FFLemon": "lemon", "FFLime": "lime", "FFGrapefruit": "grapefruit",
    "FFAvocado": "avocado", "FFMango": "mango", "FFOlive": "olive", "FFCoffee": "coffee",
    "FFPeanuts": "peanut", "FFRice": "rice", "FFBanana": "banana", "FFPineapple": "pineapple",
    "FFGrapes": "grape", "FFGinger": "ginger",
}
KINDS = (("sprite", 0), ("unhealthySprite", 8), ("dyingSprite", 16), ("deadSprite", 24))


#: tiledef ids as the batch build assigned them (2002 upward in this order; the .tiles
#: file itself only carries its internal tileset id, and each build overwrites the
#: dist mod.info, so the mapping is kept here). Vanilla farming tiles carry exactly
#: BlocksPlacement + attachedFloor (+CustomName), which is the vegetation preset.
ORDER = ("apple", "pear", "peach", "cherry", "orange", "lemon", "lime", "grapefruit",
         "avocado", "mango", "olive", "coffee", "peanut", "rice", "banana", "pineapple",
         "grape", "ginger")


def tiledef_id(name: str) -> int:
    crop = re.match(r"ff_(\w+)_01$", name).group(1)
    return 2002 + ORDER.index(crop)


def main(dry: bool) -> None:
    packs = []
    lua = ["-- generated by pz-sprite-forge/examples/ff_wire_mod.py -- do not edit by hand",
           "require \"Farming/farming_vegetableconf\"",
           "if not farming_vegetableconf then return end", ""]
    for key, crop in CROPS.items():
        name = f"ff_{crop}_01"
        pack = DIST / "texturepacks" / f"{name}.pack"
        tiles = DIST / f"{name}.tiles"
        if not pack.exists() or not tiles.exists():
            print(f"skip {key}: {name} not built")
            continue
        tid = tiledef_id(name)
        packs.append((name, tid))
        for kind, base in KINDS:
            names = ", ".join(f'"{name}_{base + i}"' for i in range(8))
            lua.append(f'farming_vegetableconf.{kind}["{key}"] = {{ {names} }}')
        lua.append(f'farming_vegetableconf.props["{key}"].texture = "{name}_6"')
        lua.append("")
        if not dry:
            (MOD_MEDIA / "texturepacks").mkdir(parents=True, exist_ok=True)
            shutil.copy2(pack, MOD_MEDIA / "texturepacks" / pack.name)
            shutil.copy2(tiles, MOD_MEDIA / tiles.name)
    info_path = MOD / "42" / "mod.info"
    info = [ln for ln in info_path.read_text(encoding="utf-8").splitlines()
            if not ln.startswith(("pack=", "tiledef="))]
    for name, tid in packs:
        info.append(f"pack={name}")
        info.append(f"tiledef={name} {tid}")
    print(f"{len(packs)} packs; mod.info gets {2 * len(packs)} lines; lua {len(lua)} lines")
    if dry:
        print("\n".join(lua[:12]), "\n...")
        return
    info_path.write_text("\n".join(info) + "\n", encoding="utf-8")
    LUA.write_text("\n".join(lua) + "\n", encoding="utf-8")
    print("wrote", info_path, "and", LUA)


if __name__ == "__main__":
    main("--dry-run" in sys.argv)
